### ISSUE TITLE
How to get separate stylesheets for server-side components?

### ISSUE THREAD

**Issue by wowselim** [quarkiverse/quarkus-web-bundler#191]
Hey,

I've been following the guide on the docs and noticed that all the stylesheets for server-side components are combined into one css resource. This means that even if a page only uses one component it imports the stylesheets for all components. I guess this also applies to the js?

https://docs.quarkiverse.io/quarkus-web-bundler/dev/advanced-guides.html#qute-components

Here's the root template:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Login</title>
{#bundle /}
</head>
<body>
<h1>Login</h1>

{#login /}
</body>
</html>
```

Here's the css that's included on that page:

```css
/* components/login/login.scss */
form {
  background-color: #fff;
  border: 5px solid #000;
}

/* components/sidebar/sidebar.module.scss */
* {
  color: blue !important;
}
/*# sourceMappingURL=/static/bundle/components-TCCAMGQL.css.map */
```

Notice how the template doesn't use the sidebar component.
